.\" @(#)optrwsgw.1 2008/10/02 NIST
.\" I Image Group
.\" Craig Watson
.\"
.TH OPTRWSGW 1 "02 October 2008" "NIST" "NBIS Reference Manual"
.SH NAME
optrwsgw \- optimizes regional weights to be applied to eigenvectors
.SH SYNOPSIS
.B optrwsgw
.I <1> <2> <3> <4> <5> <6> <7> <8> <9> <10> <11>

.SH DESCRIPTION
.B optrwsgw
is a program executed by \fBoptrws\fR in order to parallelize 
computations required for estimation of the gradient of a fingerprint
image. Users should \fBnot\fR execute this program directly. 

.SH OPTIONS
.TP
.I <1>
the first argument provided by \fBoptrws\fR

.TP
.I <2>
the second argument provided by \fBoptrws\fR

.TP
.I <3>
the third argument provided by \fBoptrws\fR

.TP
.I <4>
the fourth argument provided by \fBoptrws\fR

.TP
.I <5>
the fifth argument provided by \fBoptrws\fR

.TP
.I <6>
the sixth argument provided by \fBoptrws\fR

.TP
.I <7>
the seventh argument provided by \fBoptrws\fR

.TP
.I <8>
the eighth argument provided by \fBoptrws\fR

.TP
.I <9>
the ninth argument provided by \fBoptrws\fR

.TP
.I <10>
the tenth argument provided by \fBoptrws\fR

.TP
.I <11>
the eleventh argument provided by \fBoptrws\fR

.SH SEE ALSO
.BR cwsq (1),
.BR wrwsqcom (1)

.SH AUTHOR
NIST/ITL/DIV894/Image Group
